spring:
  datasource:
    url: jdbc:mysql://${mysql.host}/vaccines?createDatabaseIfNotExist=true
    username: ${mysql.username}
    password: ${mysql.password}
  profiles:
    active: dev
  liquibase:
    change-log: liquibase/master.yaml
  jpa:
    show-sql: ${show-sql:false}
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
server:
  port: 8080